%spark.dep
z.reset()
z.load("org.apache.streams:streams-core:0.4-incubating")
z.load("org.apache.streams:streams-converters:0.4-incubating")
z.load("org.apache.streams:streams-pojo:0.4-incubating")
z.load("org.apache.streams:streams-provider-twitter:0.4-incubating")
z.load("org.apache.streams:streams-provider-facebook:0.4-incubating")
z.load("org.apache.streams:streams-provider-youtube:0.4-incubating")
z.load("org.apache.streams:google-gplus:0.4-incubating")
